### ISSUE TITLE
Non-causal errors for scrambled samples

### ISSUE THREAD

**Issue by stefan-schroedl** [facebookresearch/InvariantRiskMinimization#5]
Hi,

I tried to reproduce Fig. 4 from the paper, the noncausal panels for the cases with scrambling (FOS, FES, POS, PES) are empty. The reason is that the noncausal variables are identified by finding zero weights
[here](https://github.com/facebookresearch/InvariantRiskMinimization/blob/master/code/experiment_synthetic/main.py#L26), but after scrambling these are removed. I think the errors should be determined by applying the scrambling on the model weights first. Obviously the figure in the paper does contain graphs, could you be so kind to update the code you used? Thank you!

**Comment by uzairakbar** [comment]
@stefan-schroedl I had the same issue. It seems they are [correctly scrambling the true weights](https://github.com/facebookresearch/InvariantRiskMinimization/blob/master/code/experiment_synthetic/sem.py#L42) before calculating the causal/non-causal errors, but the issue is that once the weights are scrambled, you can't retrieve the causal and non-causal weights to calculate each error separately. I think a better approach would be to "unscramble" the solution weights before comparing with true weights. I did this and found that my non-causal errors were comparable to the ones in the paper. However, then the causal errors were no longer comparable. It seems the scrambling results in Figure 4 of the paper might need an update (or maybe I'm doing something wrong in reproducing the results?).
